export const ONG_DETAILS: Record<string, any> = {
  'WWF Brasil': {
    id: 1,
    icon: '🐼',
    logo: require('@/img/wwf.jpg'),
    cor: '#15803d',
    corClara: '#dcfce7',
    fundacao: '1961',
    pais: 'Internacional',
    sede: 'Brasília, DF',
    site: 'https://www.wwf.org.br',
    funcionarios: '+6.000 colaboradores',
    sobre: 'O WWF (World Wildlife Fund) é uma das maiores organizações de conservação da natureza do mundo. No Brasil, atua na proteção de biomas como Amazônia, Cerrado, Pantanal e Mata Atlântica.',
    historia: 'Fundado em 1961 na Suíça. No Brasil desde 1996 desenvolvendo projetos de conservação com comunidades e parceiros.',
    tiposAceitos: ['Roupas', 'Alimentos', 'Eletrônicos'],
    horarios: ['08:00', '09:00', '10:00', '11:00', '14:00', '15:00', '16:00', '17:00'],
    atuacao: ['Amazônia', 'Cerrado', 'Espécies ameaçadas', 'Clima', 'Sustentabilidade'],
    numeros: [
      { valor: '+100', label: 'países' },
      { valor: '5 mi', label: 'apoiadores' },
      { valor: '1996', label: 'no Brasil' },
    ],
  },
  'Instituto Ayrton Senna': {
    id: 2,
    icon: '🏎️',
    logo: require('@/img/ayrtonsenna.jpg'),
    cor: '#7c3aed',
    corClara: '#ede9fe',
    fundacao: '1994',
    pais: 'Brasil',
    sede: 'São Paulo, SP',
    site: 'https://www.institutoayrtonsenna.org.br',
    funcionarios: '+300 colaboradores',
    sobre: 'O Instituto Ayrton Senna transforma a educação pública brasileira em parceria com escolas, professores e secretarias de educação.',
    historia: 'Criado em 1994 por Viviane Senna em memória do tricampeão Ayrton Senna. Já beneficiou mais de 25 milhões de alunos.',
    tiposAceitos: ['Roupas', 'Material escolar', 'Livros', 'Informática'],
    horarios: ['09:00', '10:00', '11:00', '13:00', '14:00', '15:00', '16:00'],
    atuacao: ['Educação básica', 'Alfabetização', 'Formação docente', 'Inovação'],
    numeros: [
      { valor: '+25 mi', label: 'estudantes' },
      { valor: '2.000+', label: 'municípios' },
      { valor: '100%', label: 'foco público' },
    ],
  },
  'AACD': {
    id: 3,
    icon: '🦽',
    logo: require('@/img/aacd.png'),
    cor: '#0369a1',
    corClara: '#e0f2fe',
    fundacao: '1950',
    pais: 'Brasil',
    sede: 'São Paulo, SP',
    site: 'https://www.aacd.org.br',
    funcionarios: '+2.000 colaboradores',
    sobre: 'A AACD é referência nacional em reabilitação física multidisciplinar e assistência a pessoas com deficiência físico-motora.',
    historia: 'Fundada em 1950 pelo Dr. Renato da Costa Bomfim. Oferece atendimentos de alta complexidade em ortopedia e reabilitação.',
    tiposAceitos: ['Cadeira de rodas', 'Muletas', 'Equipamentos de reabilitação', 'Brinquedos adaptados'],
    horarios: ['08:00', '09:00', '10:00', '11:00', '13:00', '14:00', '15:00', '16:00'],
    atuacao: ['Reabilitação', 'Ortopedia', 'Inclusão social', 'Tecnologia assistiva'],
    numeros: [
      { valor: '+70', label: 'anos' },
      { valor: '30 mil+', label: 'pacientes/ano' },
      { valor: '100%', label: 'gratuito SUS' },
    ],
  },
};

export const FAQ_LIST = [
  {
    pergunta: 'Como faço para doar através do GiveNet?',
    resposta: 'Acesse a aba Doação no aplicativo, escolha a ONG destino, selecione os itens que deseja doar e escolha o horário de coleta mais conveniente para você.',
  },
  {
    pergunta: 'Quais itens posso doar?',
    resposta: 'Cada ONG possui necessidades específicas: alimentos não perecíveis, roupas, materiais escolares, equipamentos de reabilitação e eletrônicos.',
  },
  {
    pergunta: 'A coleta é gratuita?',
    resposta: 'Sim! O agendamento e a intermediação no GiveNet são 100% gratuitos para doadores e ONGs.',
  },
  {
    pergunta: 'Como funciona o PIN de confirmação?',
    resposta: 'Ao registrar sua doação, um PIN de 4 dígitos e um QR Code são gerados. No momento da entrega à ONG, esse PIN é verificado para validar o status como Entregue.',
  },
  {
    pergunta: 'Posso cancelar ou reagendar uma doação?',
    resposta: 'Sim! Na aba Doação > Meus Agendamentos, você pode visualizar todas as suas doações e cancelar ou editar as que ainda estiverem com status Agendado.',
  },
  {
    pergunta: 'Como as ONGs são verificadas?',
    resposta: 'Todas as instituições parceiras passam por verificação cadastral para garantir legitimidade e transparência no destino das doações.',
  },
];
