spring.application.name=givenet

# =============================================
# PRODUCAO / ITB (SQL Server com autenticacao SQL)
# =============================================
#spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=givenet;encrypt=false;trustServerCertificate=true
#spring.datasource.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver
#spring.datasource.username=sa
#spring.datasource.password=@ITB123456

# =============================================
# LOCAL - NOTEBOOK (SQL Server com autenticacao Windows)
# =============================================
spring.datasource.url=jdbc:sqlserver://localhost;instanceName=SQLEXPRESS;databaseName=givenet;integratedSecurity=true;encrypt=false;trustServerCertificate=true
spring.datasource.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.datasource.username=
spring.datasource.password=

spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8080